#!/bin/bash
export $(cat .env | xargs)
echo "# Youtube Advertisements Regex
# ^r[0123456789]+((-{3})|(.))sn-.{8}.googlevideo.com$
# r*---sn-********.googlevideo.com
# redirector.googlevideo.com
# List Below Generated by DNS Subdomain Query Updated `date`" > youtube.txt
curl -s --request GET \
--url "https://api.securitytrails.com/v1/domain/googlevideo.com/subdomains?apikey=$API_KEY" | jq -r '.subdomains.[]' | sed 's/$/.googlevideo.com/' >> youtube.txt